import { createHash,randomBytes } from "node:crypto";import { createServiceClient } from "@/supabase";import { StudioPersistenceError } from "./repository";
function db(){const c=createServiceClient();if(!c)throw new StudioPersistenceError("Guest persistence is not configured.");return c;}const hash=(t:string)=>createHash("sha256").update(t).digest("hex");
async function issueInviteToken(episodeId:string,guestId:string){const c=db();await c.from("studio_guest_invites").update({status:"revoked"}).eq("guest_id",guestId).eq("status","active");const token=randomBytes(32).toString("base64url");const{error}=await c.from("studio_guest_invites").insert({episode_id:episodeId,guest_id:guestId,token_hash:hash(token),expires_at:new Date(Date.now()+7*86400000).toISOString()});if(error)throw new StudioPersistenceError(error.message);return token;}
export async function listGuests(episodeId:string){const {data,error}=await db().from("studio_episode_guests").select("*, studio_people(*)").eq("episode_id",episodeId).order("created_at");if(error)throw new StudioPersistenceError(error.message);return data??[];}
export async function inviteGuest(input:{episodeId:string;name:string;email?:string}){const c=db();let personId:string|undefined;if(input.email){const {data:existing}=await c.from("studio_people").select("id").eq("email",input.email).maybeSingle();if(existing)personId=existing.id;}if(!personId){const {data:p,error}=await c.from("studio_people").insert({name:input.name.trim(),email:input.email?.trim()||null}).select("id").single();if(error)throw new StudioPersistenceError(error.message);personId=p.id;}const {data:g,error:gError}=await c.from("studio_episode_guests").insert({episode_id:input.episodeId,person_id:personId,display_name:input.name.trim()}).select("*").single();if(gError)throw new StudioPersistenceError(gError.message);const token=await issueInviteToken(input.episodeId,g.id);return {guest:g,token};}
export async function renewGuestInvite(episodeId:string,guestId:string){const c=db();const{data:guest,error}=await c.from("studio_episode_guests").select("*, studio_people(*)").eq("id",guestId).eq("episode_id",episodeId).maybeSingle();if(error)throw new StudioPersistenceError(error.message);if(!guest)throw new StudioPersistenceError("Guest not found.");return{guest,token:await issueInviteToken(episodeId,guestId)};}
export async function resolveGuestInvite(token:string){const c=db();const {data:invite,error}=await c.from("studio_guest_invites").select("*, studio_episode_guests(*), studio_episodes(title,status,notes,scheduled_at)").eq("token_hash",hash(token)).eq("status","active").maybeSingle();if(error)throw new StudioPersistenceError(error.message);if(!invite||invite.expires_at&&new Date(invite.expires_at)<new Date())return null;return invite;}
export async function setGuestState(guestId:string,state:"connecting"|"green_room"|"private"|"queued"|"live"|"disconnected"|"ended"){const {data,error}=await db().from("studio_episode_guests").update({state}).eq("id",guestId).select("*").single();if(error)throw new StudioPersistenceError(error.message);return data;}
export async function listGuestMessages(episodeId:string,guestId?:string){let q=db().from("studio_guest_messages").select("*").eq("episode_id",episodeId).order("created_at");if(guestId)q=q.or(`guest_id.eq.${guestId},guest_id.is.null`);const{data,error}=await q;if(error)throw new StudioPersistenceError(error.message);return data??[];}
export async function sendGuestMessage(input:{episodeId:string;guestId?:string;senderRole:"guest"|"host"|"producer";senderUserId?:string;body:string}){const{data,error}=await db().from("studio_guest_messages").insert({episode_id:input.episodeId,guest_id:input.guestId??null,sender_role:input.senderRole,sender_user_id:input.senderUserId??null,body:input.body.trim()}).select("*").single();if(error)throw new StudioPersistenceError(error.message);return data;}
export async function getGuestExperience(token:string){const invite=await resolveGuestInvite(token);if(!invite)return null;const guest=invite.studio_episode_guests as {id:string;episode_id:string;display_name:string;state:string};const c=db();const[{data:session},{data:messages},{data:otherGuests},{data:liveQuestion}]=await Promise.all([c.from("studio_sessions").select("id,status,studio_session_state(state)").eq("episode_id",guest.episode_id).in("status",["green_room","active","created"]).order("created_at",{ascending:false}).limit(1).maybeSingle(),c.from("studio_guest_messages").select("*").eq("episode_id",guest.episode_id).or(`guest_id.eq.${guest.id},guest_id.is.null`).order("created_at"),c.from("studio_episode_guests").select("id,display_name,state").eq("episode_id",guest.episode_id).neq("id",guest.id),c.from("live_questions").select("id,body,display_name,anonymous_to_audience").eq("episode_id",guest.episode_id).eq("status","live").order("updated_at",{ascending:false}).limit(1).maybeSingle()]);const relation=session?.studio_session_state as unknown;let state:Record<string,unknown>|null=null;if(Array.isArray(relation)){const first=relation[0] as {state?:Record<string,unknown>}|undefined;state=first?.state??null;}else if(relation&&typeof relation==="object"){state=(relation as {state?:Record<string,unknown>}).state??null;}const cueIds=[state?.currentCueId,state?.nextCueId].filter((id):id is string=>typeof id==="string"&&id.length>0);let cueMap=new Map<string,{id:string;label:string;presenter_notes?:string|null}>();if(cueIds.length){const{data:cues}=await c.from("studio_cues").select("id,label,presenter_notes").in("id",cueIds);cueMap=new Map((cues??[]).map(cue=>[cue.id,cue]));}return{invite,guest,session:session??null,programState:state,currentCue:typeof state?.currentCueId==="string"?cueMap.get(state.currentCueId)??null:null,nextCue:typeof state?.nextCueId==="string"?cueMap.get(state.nextCueId)??null:null,messages:messages??[],otherGuests:otherGuests??[],liveQuestion:liveQuestion??null};}
