"use client";

type LKTrack={kind?:string;attach:()=>HTMLMediaElement;detach:()=>HTMLMediaElement[]};
type LKParticipant={identity:string;name?:string;trackPublications?:Map<string,{track?:LKTrack;isSubscribed?:boolean}>};
type LKRoom={connect:(url:string,token:string,options?:Record<string,unknown>)=>Promise<void>;disconnect:()=>void;localParticipant:{publishTrack:(track:MediaStreamTrack,options?:Record<string,unknown>)=>Promise<unknown>};remoteParticipants:Map<string,LKParticipant>;on:(event:string,handler:(...args:any[])=>void)=>LKRoom};
type LKGlobal={Room:new(options?:Record<string,unknown>)=>LKRoom;RoomEvent:Record<string,string>;Track:{Kind:{Video:string;Audio:string};Source:{Camera:string;Microphone:string}}};
declare global{interface Window{LivekitClient?:LKGlobal;__agLiveKitLoad?:Promise<LKGlobal>;}}
const SDK="https://cdn.jsdelivr.net/npm/livekit-client@2.21.0/dist/livekit-client.umd.min.js";
export type LiveKitConnection={room:LKRoom;disconnect:()=>void};

export function loadLiveKit():Promise<LKGlobal>{if(window.LivekitClient)return Promise.resolve(window.LivekitClient);if(window.__agLiveKitLoad)return window.__agLiveKitLoad;window.__agLiveKitLoad=new Promise((resolve,reject)=>{const existing=document.querySelector(`script[src="${SDK}"]`) as HTMLScriptElement|null;const script=existing??document.createElement("script");script.src=SDK;script.async=true;script.onload=()=>window.LivekitClient?resolve(window.LivekitClient):reject(new Error("LiveKit loaded without client global"));script.onerror=()=>reject(new Error("Unable to load remote media client"));if(!existing)document.head.appendChild(script);});return window.__agLiveKitLoad;}

export async function publishGuestStream(config:{url:string;token:string},stream:MediaStream,onState?:(state:string)=>void):Promise<LiveKitConnection>{const lk=await loadLiveKit();const room=new lk.Room({adaptiveStream:true,dynacast:true});const state=(s:string)=>onState?.(s);room.on(lk.RoomEvent.Reconnecting,()=>state("reconnecting"));room.on(lk.RoomEvent.Reconnected,()=>state("connected"));room.on(lk.RoomEvent.Disconnected,()=>state("disconnected"));state("connecting");await room.connect(config.url,config.token,{autoSubscribe:true});for(const track of stream.getVideoTracks())await room.localParticipant.publishTrack(track,{source:lk.Track.Source.Camera,simulcast:true,name:"ag-camera"});for(const track of stream.getAudioTracks())await room.localParticipant.publishTrack(track,{source:lk.Track.Source.Microphone,name:"ag-microphone"});state("connected");return{room,disconnect:()=>room.disconnect()};}

export async function subscribeStudioRoom(config:{url:string;token:string},handlers:{onVideo:(identity:string,name:string,element:HTMLMediaElement)=>void;onAudio:(identity:string,element:HTMLMediaElement)=>void;onRemove:(identity:string)=>void;onParticipants?:(participants:Array<{identity:string;name:string}>)=>void}):Promise<LiveKitConnection>{const lk=await loadLiveKit();const room=new lk.Room({adaptiveStream:true});const report=()=>handlers.onParticipants?.([...room.remoteParticipants.values()].map(p=>({identity:p.identity,name:p.name||p.identity})));const attach=(track:LKTrack,participant:LKParticipant)=>{const el=track.attach();if(track.kind===lk.Track.Kind.Video)handlers.onVideo(participant.identity,participant.name||participant.identity,el);else if(track.kind===lk.Track.Kind.Audio)handlers.onAudio(participant.identity,el);};room.on(lk.RoomEvent.TrackSubscribed,(track:any,_pub:any,participant:any)=>attach(track,participant));room.on(lk.RoomEvent.ParticipantConnected,()=>report());room.on(lk.RoomEvent.ParticipantDisconnected,(participant:any)=>{handlers.onRemove(participant.identity);report();});await room.connect(config.url,config.token,{autoSubscribe:true});for(const participant of room.remoteParticipants.values()){participant.trackPublications?.forEach(pub=>{if(pub.isSubscribed&&pub.track)attach(pub.track,participant);});}report();return{room,disconnect:()=>room.disconnect()};}
