import { createServiceClient } from "@/supabase";
import { StudioPersistenceError } from "./repository";

function db(){ const client=createServiceClient(); if(!client) throw new StudioPersistenceError("AG Live persistence is not configured."); return client; }
export async function getLiveAudience(episodeId:string){ const client=db(); const [{data:questions,error:qError},{data:polls,error:pError}]=await Promise.all([client.from("live_questions").select("*, live_question_votes(user_id)").eq("episode_id",episodeId).order("created_at",{ascending:false}),client.from("live_polls").select("*, live_poll_options(*), live_poll_responses(option_id,user_id)").eq("episode_id",episodeId).order("created_at",{ascending:false})]); if(qError)throw new StudioPersistenceError(qError.message); if(pError)throw new StudioPersistenceError(pError.message); return {questions:(questions??[]).map(q=>({...q,vote_count:Array.isArray(q.live_question_votes)?q.live_question_votes.length:0})),polls:polls??[]}; }
export async function submitQuestion(input:{episodeId:string;userId:string;displayName?:string;body:string;anonymous?:boolean}){ const {data,error}=await db().from("live_questions").insert({episode_id:input.episodeId,user_id:input.userId,display_name:input.displayName,body:input.body.trim(),anonymous_to_audience:Boolean(input.anonymous)}).select("*").single(); if(error)throw new StudioPersistenceError(error.message); return data; }
export async function setQuestionStatus(questionId:string,status:"approved"|"queued"|"live"|"answered"|"dismissed"){ const {data,error}=await db().from("live_questions").update({status}).eq("id",questionId).select("*").single(); if(error)throw new StudioPersistenceError(error.message); return data; }
export async function toggleQuestionVote(questionId:string,userId:string){ const client=db(); const {data}=await client.from("live_question_votes").select("question_id").eq("question_id",questionId).eq("user_id",userId).maybeSingle(); if(data){const {error}=await client.from("live_question_votes").delete().eq("question_id",questionId).eq("user_id",userId);if(error)throw new StudioPersistenceError(error.message);return false;} const {error}=await client.from("live_question_votes").insert({question_id:questionId,user_id:userId});if(error)throw new StudioPersistenceError(error.message);return true; }
export async function createPoll(input:{episodeId:string;userId:string;question:string;options:string[]}){ const client=db(); const {data:poll,error}=await client.from("live_polls").insert({episode_id:input.episodeId,question:input.question.trim(),created_by:input.userId}).select("*").single();if(error)throw new StudioPersistenceError(error.message); const rows=input.options.map((label,i)=>({poll_id:poll.id,label:label.trim(),sort_order:i}));const {error:oError}=await client.from("live_poll_options").insert(rows);if(oError)throw new StudioPersistenceError(oError.message);return poll; }
export async function setPollState(pollId:string,input:{status?:"draft"|"scheduled"|"open"|"closed"|"archived";showResults?:boolean}){ const patch:Record<string,unknown>={};if(input.status)patch.status=input.status;if(typeof input.showResults==="boolean")patch.show_results=input.showResults;const {data,error}=await db().from("live_polls").update(patch).eq("id",pollId).select("*").single();if(error)throw new StudioPersistenceError(error.message);return data; }
export async function answerPoll(input:{pollId:string;optionId:string;userId:string}){ const client=db();const {data:poll,error:pError}=await client.from("live_polls").select("status,allow_answer_change").eq("id",input.pollId).single();if(pError||!poll)throw new StudioPersistenceError(pError?.message??"Poll not found");if(poll.status!=="open")throw new StudioPersistenceError("This poll is not open.");const {data:existing}=await client.from("live_poll_responses").select("option_id").eq("poll_id",input.pollId).eq("user_id",input.userId).maybeSingle();if(existing&&!poll.allow_answer_change)throw new StudioPersistenceError("Your response is already recorded.");const {error}=await client.from("live_poll_responses").upsert({poll_id:input.pollId,option_id:input.optionId,user_id:input.userId},{onConflict:"poll_id,user_id"});if(error)throw new StudioPersistenceError(error.message);return true; }
