import{NextResponse}from"next/server";import{z}from"zod";import{getAdminAccess}from"@/auth";import{getEpisode}from"@/studio/repository";import{inviteGuest,listGuests,listGuestMessages,renewGuestInvite,sendGuestMessage,setGuestState}from"@/studio/guest-repository";import{sendGuestInviteEmail}from"@/studio/invite-email";
async function producer(){const a=await getAdminAccess();return a.state==="allowed"&&a.user?.id&&["owner","admin","editor"].includes(a.role??"")?a:null;}
export async function GET(_r:Request,{params}:{params:Promise<{episodeId:string}>}){if(!await producer())return NextResponse.json({error:"Forbidden"},{status:403});const{episodeId}=await params;return NextResponse.json({guests:await listGuests(episodeId),messages:await listGuestMessages(episodeId)});}
const A=z.discriminatedUnion("type",[
z.object({type:z.literal("invite"),name:z.string().trim().min(1).max(100),email:z.string().email().optional().or(z.literal("")),sendEmail:z.boolean().optional()}),
z.object({type:z.literal("resend"),guestId:z.string().uuid()}),
z.object({type:z.literal("message"),guestId:z.string().uuid().optional(),body:z.string().trim().min(1).max(1500)}),
z.object({type:z.literal("state"),guestId:z.string().uuid(),state:z.enum(["connecting","green_room","private","queued","live","disconnected","ended"])})]);
async function absoluteJoinUrl(request:Request,token:string){const configured=process.env.NEXT_PUBLIC_SITE_URL?.replace(/\/$/,"");if(configured)return`${configured}/guest/${token}`;const url=new URL(request.url);return`${url.protocol}//${url.host}/guest/${token}`;}
async function mailInvite(request:Request,episodeId:string,result:{guest:any;token:string}){const snapshot=await getEpisode(episodeId);const person=result.guest.studio_people??null;const guests=await listGuests(episodeId);const full=guests.find((g:any)=>g.id===result.guest.id);const email=full?.studio_people?.email??person?.email;if(!email)throw new Error("Add an email address before sending this invitation.");return sendGuestInviteEmail({to:email,guestName:result.guest.display_name,episodeTitle:snapshot?.episode.title??"Apostolic Guide Live",episodeNotes:snapshot?.episode.notes,scheduledAt:snapshot?.episode.scheduled_at,joinUrl:await absoluteJoinUrl(request,result.token)});}
export async function POST(r:Request,{params}:{params:Promise<{episodeId:string}>}){const access=await producer();if(!access)return NextResponse.json({error:"Forbidden"},{status:403});const p=A.safeParse(await r.json().catch(()=>null));if(!p.success)return NextResponse.json({error:"Invalid guest action"},{status:400});const{episodeId}=await params;try{if(p.data.type==="invite"){const result=await inviteGuest({episodeId,name:p.data.name,email:p.data.email||undefined});let emailResult=null;if(p.data.sendEmail&&p.data.email)emailResult=await mailInvite(r,episodeId,result);return NextResponse.json({...result,guestUrl:await absoluteJoinUrl(r,result.token),emailResult},{status:201});}if(p.data.type==="resend"){const result=await renewGuestInvite(episodeId,p.data.guestId);const emailResult=await mailInvite(r,episodeId,result);return NextResponse.json({...result,guestUrl:await absoluteJoinUrl(r,result.token),emailResult});}if(p.data.type==="message")return NextResponse.json({message:await sendGuestMessage({episodeId,guestId:p.data.guestId,senderRole:"producer",senderUserId:access.user!.id,body:p.data.body})},{status:201});if(p.data.state==="live"){const guests=await listGuests(episodeId);const guest=guests.find((g:any)=>g.id===p.data.guestId);if(!guest)return NextResponse.json({error:"Guest not found"},{status:404});if(guest.media_state!=="connected")return NextResponse.json({error:"Guest remote feed is not connected. Keep them queued until media is ready."},{status:409});}return NextResponse.json({guest:await setGuestState(p.data.guestId,p.data.state)});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Guest action failed"},{status:500});}}
