import { NextResponse } from "next/server";
import { z } from "zod";
import { createSupabaseServerClient } from "@/supabase";
import { getEpisode, StudioPersistenceError } from "@/studio/repository";
import { answerPoll, getLiveAudience, submitQuestion, toggleQuestionVote } from "@/studio/live-repository";

async function viewer(){const supabase=await createSupabaseServerClient();if(!supabase)return null;const {data}=await supabase.auth.getUser();return data.user??null;}
async function allowedEpisode(id:string,userId?:string){const snapshot=await getEpisode(id);if(!snapshot)return null;const mode=snapshot.episode.access_mode;if(mode==="private")return null;if((mode==="account"||mode==="members")&&!userId)return {snapshot,needsLogin:true};return {snapshot,needsLogin:false};}
export async function GET(_request:Request,{params}:{params:Promise<{episodeId:string}>}){try{const {episodeId}=await params;const user=await viewer();const access=await allowedEpisode(episodeId,user?.id);if(!access)return NextResponse.json({error:"Live session not available"},{status:404});if(access.needsLogin)return NextResponse.json({episode:access.snapshot.episode,needsLogin:true},{status:401});return NextResponse.json({episode:access.snapshot.episode,user:user?{id:user.id,email:user.email}:null,audience:await getLiveAudience(episodeId)});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Unable to load live session"},{status:error instanceof StudioPersistenceError?503:500});}}
const Action=z.discriminatedUnion("type",[
 z.object({type:z.literal("question.submit"),body:z.string().trim().min(1).max(1000),anonymous:z.boolean().optional(),displayName:z.string().trim().max(80).optional()}),
 z.object({type:z.literal("question.vote"),questionId:z.string().uuid()}),
 z.object({type:z.literal("poll.answer"),pollId:z.string().uuid(),optionId:z.string().uuid()})
]);
export async function POST(request:Request,{params}:{params:Promise<{episodeId:string}>}){const user=await viewer();if(!user)return NextResponse.json({error:"Sign in with your Apostolic Guide account to participate."},{status:401});const parsed=Action.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"Invalid live action"},{status:400});try{const {episodeId}=await params;const access=await allowedEpisode(episodeId,user.id);if(!access)return NextResponse.json({error:"Live session not available"},{status:404});const action=parsed.data;if(action.type==="question.submit")return NextResponse.json({question:await submitQuestion({episodeId,userId:user.id,displayName:action.displayName||user.user_metadata?.display_name||user.email?.split("@")[0],body:action.body,anonymous:action.anonymous})},{status:201});if(action.type==="question.vote")return NextResponse.json({voted:await toggleQuestionVote(action.questionId,user.id)});await answerPoll({pollId:action.pollId,optionId:action.optionId,userId:user.id});return NextResponse.json({recorded:true});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Unable to update live session"},{status:error instanceof StudioPersistenceError?409:500});}}
