"use client";
import{useEffect,useRef,useState}from"react";import{subscribeStudioRoom,type LiveKitConnection}from"@/studio/livekit-client";
type Feed={identity:string;name:string;stream:MediaStream};type MediaConfig={url:string;token:string};
export function TabletMediaPreview({sessionId,sceneId,className=""}:{sessionId:string;sceneId:string;className?:string}){const[feeds,setFeeds]=useState<Feed[]>([]),[status,setStatus]=useState("connecting");const room=useRef<LiveKitConnection|null>(null);
 useEffect(()=>{let cancelled=false;async function connect(){try{const r=await fetch(`/api/studio/sessions/${sessionId}/room-media`,{cache:"no-store"});const p=await r.json();if(!r.ok||!p.configured||!p.media){setStatus("state-only");return;}const c=await subscribeStudioRoom(p.media as MediaConfig,{onVideo:(identity,name,element)=>{if(cancelled)return;const stream=element.srcObject;if(!(stream instanceof MediaStream))return;setFeeds(current=>[...current.filter(f=>f.identity!==identity),{identity,name,stream}]);},onAudio:()=>{},onRemove:identity=>setFeeds(current=>current.filter(f=>f.identity!==identity))});if(cancelled)c.disconnect();else{room.current=c;setStatus("live");}}catch{if(!cancelled)setStatus("offline");}}void connect();return()=>{cancelled=true;room.current?.disconnect();room.current=null;};},[sessionId]);
 const host=feeds.find(f=>f.identity.startsWith("host-"));const guests=feeds.filter(f=>f.identity.startsWith("guest-"));const tile=(feed:Feed|undefined,label:string)=><PreviewTile key={feed?.identity??label} feed={feed} label={label}/>;const scene=sceneId||"host-full";
 return <div className={`ag-tablet-preview ${className}`}><div className="ag-tablet-preview-stage">{scene==="panel-grid"?<div className="ag-tablet-preview-grid">{tile(host,"HOST")}{tile(guests[0],"GUEST 1")}{tile(guests[1],"GUEST 2")}{tile(guests[2],"GUEST 3")}</div>:scene==="split"||scene.startsWith("panel-")?<div className="ag-tablet-preview-split">{tile(host,"HOST")}{tile(guests[0],"GUEST")}</div>:scene==="scripture-full"?<div className="ag-tablet-preview-graphic">SCRIPTURE</div>:scene==="question-full"?<div className="ag-tablet-preview-graphic">LIVE QUESTION</div>:scene==="holding"?<div className="ag-tablet-preview-graphic">TECHNICAL HOLD</div>:scene==="black"?<div className="ag-tablet-preview-black"/>:tile(host,"HOST")}</div><footer><span className={`preview-dot ${status}`}/><strong>{scene.replaceAll("-"," ")}</strong><small>{status==="live"?"ROOM PREVIEW":status==="state-only"?"STATE PREVIEW":"PREVIEW CONNECTING"}</small></footer></div>;
}
function PreviewTile({feed,label}:{feed?:Feed;label:string}){const ref=useRef<HTMLVideoElement>(null);useEffect(()=>{if(ref.current&&feed?.stream)ref.current.srcObject=feed.stream;},[feed?.stream]);return <div className="ag-tablet-preview-tile">{feed?<video ref={ref} autoPlay muted playsInline/>:<div><span>AG</span><small>{label}</small></div>}{feed?<b>{feed.name}</b>:null}</div>}
