"use client";
import{useEffect,useMemo,useState}from"react";import{ChevronLeft,ChevronRight,Monitor,Radio,Users,BookOpen,MessageSquare,PauseCircle,ShieldAlert,Sun,Moon,Sparkles,Wifi,WifiOff}from"lucide-react";import type{StudioProgramState}from"@/studio/types";import{TabletMediaPreview}from"../../tablet-media-preview";
type Cue={id:string;label:string;position:number;presenter_notes?:string|null;enabled:boolean};type Question={id:string;body:string;status:string;vote_count:number};type Poll={id:string;question:string;status:string;show_results:boolean};type Guest={id:string;display_name:string;state:string;media_state?:string};type Snapshot={session:{studio_episodes?:{title?:string}|null};state:StudioProgramState;cues:Cue[];audience:{questions:Question[];polls:Poll[]};guests:Guest[]};
const scenes=[{id:"host-full",label:"HOST",icon:Radio},{id:"split",label:"HOST + GUEST",icon:Users},{id:"panel-grid",label:"PANEL GRID",icon:Users},{id:"host-scripture",label:"HOST + SCRIPTURE",icon:BookOpen},{id:"scripture-full",label:"SCRIPTURE",icon:BookOpen},{id:"panel-question",label:"PANEL + QUESTION",icon:MessageSquare},{id:"question-full",label:"QUESTION",icon:MessageSquare},{id:"pathway-cta",label:"PATHWAY CTA",icon:Monitor},{id:"holding",label:"HOLD",icon:PauseCircle},{id:"black",label:"BLACKOUT",icon:ShieldAlert}];
export default function ProducerController({sessionId}:{sessionId:string}){const[data,setData]=useState<Snapshot|null>(null),[busy,setBusy]=useState(false),[connected,setConnected]=useState(true),[theme,setTheme]=useState<"dark"|"light">("dark"),[autoMode,setAutoMode]=useState<"off"|"assist"|"auto">("off"),[error,setError]=useState("");
 useEffect(()=>{const saved=localStorage.getItem("ag-controller-theme");if(saved==="light")setTheme("light");let alive=true;let timer:ReturnType<typeof setTimeout>;async function poll(){try{const r=await fetch(`/api/studio/sessions/${sessionId}/tablet`,{cache:"no-store"});if(!r.ok)throw 0;const p=await r.json();if(alive){setData(p);setConnected(true);}}catch{if(alive)setConnected(false);}finally{if(alive)timer=setTimeout(poll,700);}}void poll();return()=>{alive=false;clearTimeout(timer);};},[sessionId]);
 useEffect(()=>{let alive=true;async function readAuto(){try{const r=await fetch(`/api/studio/sessions/${sessionId}/auto-director`,{cache:"no-store"});if(r.ok){const p=await r.json();if(alive)setAutoMode(p.settings?.enabled?p.settings?.mode:"off");}}catch{}}void readAuto();const id=setInterval(()=>void readAuto(),1800);return()=>{alive=false;clearInterval(id);};},[sessionId]);
 function click(){try{navigator.vibrate?.(18);}catch{}}
 async function takeCue(id:string){if(busy)return;click();setBusy(true);setError("");try{const r=await fetch(`/api/studio/sessions/${sessionId}/cues/${id}/take`,{method:"POST"});const p=await r.json();if(!r.ok)throw new Error(p.error??"TAKE failed");setData(d=>d?{...d,state:p.state??d.state}:d);}catch(e){setError(e instanceof Error?e.message:"TAKE failed");}finally{setBusy(false);}}
 async function action(type:string,payload:Record<string,unknown>={}){if(!data||busy)return;click();setBusy(true);setError("");try{const actionId=crypto.randomUUID();const r=await fetch(`/api/studio/sessions/${sessionId}/action`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({actionId,expectedVersion:data.state.version,actions:[{id:`${actionId}:0`,cueId:"tablet",position:0,type,payload}]})});const p=await r.json();if(!r.ok)throw new Error(p.error??"Control failed");if(p.state)setData(d=>d?{...d,state:p.state}:d);}catch(e){setError(e instanceof Error?e.message:"Control failed");}finally{setBusy(false);}}
 async function scene(id:string){void fetch(`/api/studio/sessions/${sessionId}/auto-director`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:"manual_override",seconds:30})});await action("scene.set",{sceneId:id});}
 async function changeAuto(mode:"off"|"assist"|"auto"){click();setAutoMode(mode);await fetch(`/api/studio/sessions/${sessionId}/auto-director`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:"settings",mode})});}
 async function audience(payload:Record<string,unknown>){click();await fetch(`/api/studio/episodes/${data?.state.episodeId}/audience`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});}
 const cues=useMemo(()=>[...(data?.cues??[])].filter(c=>c.enabled).sort((a,b)=>a.position-b.position),[data?.cues]);const index=data?.state.currentCueId?cues.findIndex(c=>c.id===data.state.currentCueId):-1;const current=index>=0?cues[index]:undefined;const next=data?.state.nextCueId?cues.find(c=>c.id===data.state.nextCueId):cues[index+1]??cues[0];const prev=index>0?cues[index-1]:undefined;const live=data?.state.status==="active";const questions=(data?.audience.questions??[]).filter(q=>["approved","queued","live"].includes(q.status)).sort((a,b)=>b.vote_count-a.vote_count).slice(0,4);const polls=(data?.audience.polls??[]).filter(p=>p.status==="open"||p.status==="closed").slice(0,3);
 function themeToggle(){const n=theme==="dark"?"light":"dark";setTheme(n);localStorage.setItem("ag-controller-theme",n);}
 if(!data)return <main className={`ag-controller ${theme}`}><div className="controller-boot"><span className="led amber"/>CONNECTING TO AG STUDIO</div></main>;
 return <main className={`ag-controller ${theme}`}><header className="controller-top"><div><span className="controller-logo">AG</span><div><strong>PRODUCER CONTROLLER</strong><small>{data.session.studio_episodes?.title??"AG Broadcast Studio"}</small></div></div><div className="controller-status"><span className={`status-pill ${connected?"ok":"bad"}`}>{connected?<Wifi/>:<WifiOff/>}{connected?"SYNC":"OFFLINE"}</span><span className={`status-pill ${live?"live":"idle"}`}><i/>{live?"LIVE":"NOT LIVE"}</span><button onClick={themeToggle}>{theme==="dark"?<Sun/>:<Moon/>}</button></div></header>
 <section className="controller-dashboard"><div className="controller-left"><TabletMediaPreview sessionId={sessionId} sceneId={data.state.currentSceneId}/><div className="controller-cue-strip"><article><span>CURRENT</span><strong>{current?.label??"READY"}</strong><p>{current?.presenter_notes||"No current cue note."}</p></article><article><span>NEXT</span><strong>{next?.label??"END"}</strong><p>{next?.presenter_notes||"Ready for the next move."}</p></article></div><div className="controller-transport"><button disabled={!prev||busy} onClick={()=>prev&&takeCue(prev.id)}><ChevronLeft/> PREV</button><button className="take" disabled={!next||busy} onClick={()=>next&&takeCue(next.id)}><span className="led green"/>TAKE NEXT</button><button disabled={!next||busy} onClick={()=>next&&takeCue(next.id)}>NEXT <ChevronRight/></button></div></div>
 <aside className="controller-right"><div className="switcher-bank"><header><span>PROGRAM BUS</span><small>SCENES</small></header><div className="scene-grid">{scenes.map(({id,label,icon:Icon})=><button key={id} disabled={busy} className={`${data.state.currentSceneId===id?"active":""} ${id==="black"?"danger":""}`} onClick={()=>void scene(id)}><span className={`led ${data.state.currentSceneId===id?"red":"off"}`}/><Icon/><b>{label}</b></button>)}</div></div><div className="auto-bank"><header><Sparkles/><span>AUTO DIRECTOR</span></header><div>{(["off","assist","auto"] as const).map(m=><button key={m} className={autoMode===m?"active":""} onClick={()=>void changeAuto(m)}><span className={`led ${autoMode===m?(m==="auto"?"green":"amber"):"off"}`}/>{m.toUpperCase()}</button>)}</div></div></aside></section>
 <section className="controller-lower"><div className="controller-run"><header><strong>RUN OF SHOW</strong><span>{index+1}/{cues.length}</span></header><div>{cues.map((c,i)=><button key={c.id} className={c.id===data.state.currentCueId?"active":""} onClick={()=>void takeCue(c.id)}><span>{String(i+1).padStart(2,"0")}</span><b>{c.label}</b></button>)}</div></div><div className="controller-audience"><header><strong>LIVE QUESTIONS</strong></header>{questions.length?questions.map(q=><article key={q.id}><p>{q.body}</p><span>{q.vote_count} votes</span><div><button onClick={()=>void audience({type:"question.status",questionId:q.id,status:"live"})}>ON AIR</button><button onClick={()=>void audience({type:"question.status",questionId:q.id,status:"answered"})}>DONE</button></div></article>):<p className="empty">No approved questions.</p>}</div><div className="controller-polls"><header><strong>POLLS</strong></header>{polls.length?polls.map(p=><article key={p.id}><p>{p.question}</p><button onClick={()=>void audience({type:"poll.state",pollId:p.id,status:p.status==="open"?"closed":"open"})}>{p.status==="open"?"CLOSE":"OPEN"}</button></article>):<p className="empty">No active polls.</p>}</div></section>
 <footer className="controller-panic"><button onClick={()=>void scene("host-full")}>RETURN TO HOST</button><button onClick={()=>void action("program.clear")}>CLEAR GRAPHICS</button><button onClick={()=>void scene("holding")}>TECH HOLD</button><button className="blackout" onClick={()=>void scene("black")}><span className="led red"/>BLACKOUT</button></footer>{error?<div className="controller-error">{error}</div>:null}</main>}
