"use client";
import{useEffect,useMemo,useRef,useState}from"react";import{Camera,Mic,MicOff,Video,VideoOff,Send,MessageCircle,Users,CheckCircle2}from"lucide-react";
type Msg={id:string;sender_role:string;body:string;created_at:string};type OtherGuest={id:string;display_name:string;state:string};
export default function GuestGreenRoom({token,guestName,episodeTitle}:{token:string;guestId:string;guestName:string;episodeTitle:string}){const[ready,setReady]=useState(false),[error,setError]=useState(""),[muted,setMuted]=useState(false),[videoOff,setVideoOff]=useState(false),[state,setState]=useState("invited"),[messages,setMessages]=useState<Msg[]>([]),[others,setOthers]=useState<OtherGuest[]>([]),[liveQuestion,setLiveQuestion]=useState<{body:string}|null>(null),[chat,setChat]=useState("");const video=useRef<HTMLVideoElement>(null);const stream=useRef<MediaStream|null>(null);
 useEffect(()=>{let alive=true;async function poll(){try{const r=await fetch(`/api/guest/${token}`,{cache:"no-store"});if(r.ok){const p=await r.json();if(alive){setState(p.guest?.state??"invited");setMessages(p.messages??[]);setOthers(p.otherGuests??[]);setLiveQuestion(p.liveQuestion??null);}}}catch{} }void poll();const id=setInterval(()=>void poll(),2000);return()=>{alive=false;clearInterval(id);stream.current?.getTracks().forEach(t=>t.stop());};},[token]);
 async function action(payload:Record<string,unknown>){const r=await fetch(`/api/guest/${token}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!r.ok){const p=await r.json().catch(()=>({}));setError(p.error??"Unable to update backstage status");return false;}return true;}
 async function setup(){setError("");try{stream.current?.getTracks().forEach(t=>t.stop());const s=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:1920},height:{ideal:1080}},audio:{echoCancellation:true,noiseSuppression:true}});stream.current=s;if(video.current)video.current.srcObject=s;setReady(true);setMuted(false);setVideoOff(false);await action({type:"state",state:"green_room"});}catch(e){setError(e instanceof Error?e.message:"Camera or microphone unavailable");}}
 function toggleMute(){const next=!muted;stream.current?.getAudioTracks().forEach(t=>t.enabled=!next);setMuted(next);}function toggleVideo(){const next=!videoOff;stream.current?.getVideoTracks().forEach(t=>t.enabled=!next);setVideoOff(next);}async function send(e:React.FormEvent){e.preventDefault();if(!chat.trim())return;if(await action({type:"message",body:chat})){setChat("");}}
 const status=useMemo(()=>state==="live"?{label:"YOU ARE LIVE",tone:"live",help:"You are on the program feed."}:state==="queued"?{label:"YOU’RE UP NEXT",tone:"queued",help:"Stay ready. The producer is preparing your entrance."}:state==="private"?{label:"PRIVATE WITH HOST",tone:"private",help:"You can speak with the host off-air."}:state==="ended"?{label:"SESSION ENDED",tone:"ended",help:"Thanks for joining Apostolic Guide."}:{label:"BACKSTAGE",tone:"backstage",help:"You are not on-air."},[state]);
 return <main className="ag-guest"><div className="ag-guest-shell"><header><div><span className="ag-guest-brand">APOSTOLIC GUIDE · GUEST STUDIO</span><h1>{episodeTitle}</h1></div><div className={`ag-guest-live-state ${status.tone}`}><i/>{status.label}<small>{status.help}</small></div></header><div className="ag-guest-layout"><section className="ag-guest-stage"><div className="ag-guest-preview">{ready?<video ref={video} autoPlay muted playsInline/>:<div><Camera size={34}/><span>YOUR CAMERA</span></div>}{videoOff?<div className="ag-guest-video-off"><VideoOff size={28}/><span>Camera off</span></div>:null}</div>{error?<p className="ag-guest-error">{error}</p>:null}<div className="ag-guest-controls">{!ready?<button className="primary" onClick={setup}><Camera size={17}/><Mic size={17}/> CHECK CAMERA + MIC</button>:<><button className={muted?"active":""} onClick={toggleMute}>{muted?<MicOff/>:<Mic/>}<span>{muted?"Unmute":"Mute"}</span></button><button className={videoOff?"active":""} onClick={toggleVideo}>{videoOff?<VideoOff/>:<Video/>}<span>{videoOff?"Start video":"Stop video"}</span></button><button onClick={setup}><CheckCircle2/><span>Devices</span></button></>}</div>{liveQuestion?<div className="ag-guest-question"><span>ON-SCREEN QUESTION</span><strong>{liveQuestion.body}</strong></div>:null}<div className="ag-guest-panel-awareness"><Users size={15}/><div><strong>Panel</strong><span>{others.length?others.map(g=>`${g.display_name} · ${g.state.replace("_"," ")}`).join("   •   "):"You’re the only guest connected right now."}</span></div></div></section><aside className="ag-guest-chat"><header><MessageCircle size={16}/><div><strong>Backstage chat</strong><span>Host + producer</span></div></header><div className="ag-guest-messages">{messages.length?messages.map(m=><article key={m.id} className={m.sender_role==="guest"?"mine":"theirs"}><span>{m.sender_role==="guest"?"You":m.sender_role}</span><p>{m.body}</p></article>):<div className="ag-guest-empty">Messages from the host or producer will appear here.</div>}</div><form onSubmit={send}><input value={chat} onChange={e=>setChat(e.target.value)} placeholder="Message the host or producer…" maxLength={1500}/><button><Send size={15}/></button></form></aside></div><footer><span>{guestName}</span><small>Private guest link · {token.slice(0,4)}••••</small></footer></div></main>}
