import { NextResponse } from "next/server";
import { z } from "zod";
import { getStudioPermission } from "@/auth";
import { pathwayBySlug } from "@/pathway-catalog";
import { createServiceClient } from "@/supabase";

export const runtime = "nodejs";
export const maxDuration = 30;

const schema = z.object({
  slug: z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),
  formats: z.array(z.enum(["youtube", "vertical", "square"])).min(1).max(3)
});

function assetDetails(format: "youtube" | "vertical" | "square", pathwayTitle: string) {
  if (format === "youtube") return { type: "youtube", platform: "youtube", title: `${pathwayTitle} · YouTube` };
  if (format === "vertical") return { type: "short_video", platform: "vertical_social", title: `${pathwayTitle} · Reel / TikTok` };
  return { type: "short_video", platform: "square_social", title: `${pathwayTitle} · Square video` };
}

async function rendererCredentials(service: ReturnType<typeof createServiceClient>) {
  let token = process.env.VIDEO_STUDIO_GITHUB_TOKEN?.trim() || "";
  let repository = process.env.VIDEO_STUDIO_GITHUB_REPOSITORY?.trim() || "Elicasta/apostolic-guide-web";
  if (token || !service) return { token, repository };

  const { data, error } = await service.schema("analytics").from("integration_secrets")
    .select("name,secret")
    .in("name", ["video_studio_github_token", "video_studio_github_repository"]);
  if (error) throw new Error(error.message);
  const values = new Map((data ?? []).map((row) => [row.name, row.secret]));
  token = values.get("video_studio_github_token")?.trim() || "";
  repository = values.get("video_studio_github_repository")?.trim() || repository;
  return { token, repository };
}

export async function POST(request: Request) {
  const { access, allowed } = await getStudioPermission("manage_content");
  if (!allowed || access.state !== "allowed" || !access.user) return NextResponse.json({ error: "Forbidden" }, { status: 403 });

  const parsed = schema.safeParse(await request.json().catch(() => null));
  if (!parsed.success) return NextResponse.json({ error: "Invalid render request." }, { status: 400 });
  const pathway = pathwayBySlug(parsed.data.slug);
  if (!pathway) return NextResponse.json({ error: "Pathway not found." }, { status: 404 });

  const service = createServiceClient();
  if (!service) return NextResponse.json({ error: "Supabase service access is not configured." }, { status: 503 });

  let token = "";
  let repository = "Elicasta/apostolic-guide-web";
  try {
    ({ token, repository } = await rendererCredentials(service));
  } catch (error) {
    return NextResponse.json({ error: error instanceof Error ? error.message : "Renderer credentials could not be loaded." }, { status: 500 });
  }
  if (!token) return NextResponse.json({
    error: "Video renderer is not connected. Open Setup → Video renderer and add the GitHub Actions token first.",
    code: "renderer_not_connected",
    setupUrl: "/admin/setup#video-renderer"
  }, { status: 503 });

  const [projectResult, audioResult] = await Promise.all([
    service.from("pathway_video_projects").select("id,audio_content_hash,timeline,style").eq("pathway_slug", pathway.slug).maybeSingle(),
    service.from("pathway_audio_assets").select("audio_url,content_hash").eq("pathway_slug", pathway.slug).maybeSingle()
  ]);
  if (projectResult.error) return NextResponse.json({ error: projectResult.error.message }, { status: 500 });
  if (audioResult.error) return NextResponse.json({ error: audioResult.error.message }, { status: 500 });
  if (!projectResult.data) return NextResponse.json({ error: "Save the video timeline before rendering." }, { status: 409 });
  if (!audioResult.data?.audio_url) return NextResponse.json({ error: "Pathway audio is missing." }, { status: 409 });
  if (projectResult.data.audio_content_hash !== audioResult.data.content_hash) return NextResponse.json({ error: "The Pathway audio changed after this video timeline was saved. Review and save the timeline again before rendering." }, { status: 409 });

  const queued = [];
  for (const format of [...new Set(parsed.data.formats)]) {
    const details = assetDetails(format, pathway.title);
    const publishingAsset = await service.from("pathway_assets").insert({
      pathway_slug: pathway.slug,
      type: details.type,
      title: details.title,
      language: "en",
      status: "in_production",
      platform: details.platform,
      source_url: audioResult.data.audio_url,
      cta_type: "visit_pathway",
      destination_url: `https://www.apostolicguide.com/pathways/${pathway.slug}`,
      notes: `Generated by Video Studio from Pathway audio ${audioResult.data.content_hash}.`
    }).select("id").single();
    if (publishingAsset.error) return NextResponse.json({ error: publishingAsset.error.message }, { status: 500 });

    const snapshot = {
      version: 1,
      pathway: { slug: pathway.slug, title: pathway.title, summary: pathway.summary },
      format,
      audioUrl: audioResult.data.audio_url,
      audioContentHash: audioResult.data.content_hash,
      timeline: projectResult.data.timeline,
      style: projectResult.data.style,
      assetId: publishingAsset.data.id
    };
    const created = await service.from("pathway_video_renders").insert({
      pathway_slug: pathway.slug,
      project_id: projectResult.data.id,
      asset_id: publishingAsset.data.id,
      format,
      status: "queued",
      config_snapshot: snapshot,
      requested_by: access.user.id
    }).select("id,pathway_slug,asset_id,format,status,output_url,error,requested_at,completed_at").single();
    if (created.error) {
      await service.from("pathway_assets").update({ status: "blocked", notes: `Video Studio render row could not be created: ${created.error.message}` }).eq("id", publishingAsset.data.id);
      return NextResponse.json({ error: created.error.message }, { status: 500 });
    }

    const render = created.data;
    const dispatch = await fetch(`https://api.github.com/repos/${repository}/dispatches`, {
      method: "POST",
      headers: {
        accept: "application/vnd.github+json",
        authorization: `Bearer ${token}`,
        "content-type": "application/json",
        "user-agent": "apostolic-guide-video-studio",
        "x-github-api-version": "2022-11-28"
      },
      body: JSON.stringify({
        event_type: "pathway-video-render",
        client_payload: {
          job_id: render.id,
          asset_id: publishingAsset.data.id,
          slug: pathway.slug,
          title: pathway.title,
          format,
          audio_url: audioResult.data.audio_url,
          timeline: projectResult.data.timeline,
          style: projectResult.data.style
        }
      })
    });

    if (!dispatch.ok) {
      const detail = (await dispatch.text().catch(() => "")).slice(0, 800);
      const error = `Renderer dispatch failed (${dispatch.status})${detail ? `: ${detail}` : ""}`;
      await Promise.all([
        service.from("pathway_video_renders").update({ status: "failed", error, completed_at: new Date().toISOString() }).eq("id", render.id),
        service.from("pathway_assets").update({ status: "blocked", notes: error }).eq("id", publishingAsset.data.id)
      ]);
      return NextResponse.json({ error }, { status: 502 });
    }
    queued.push(render);
  }

  return NextResponse.json({ renders: queued });
}
