begin;

-- Rolling back Forge removes only its operator ledger rows. Persistent Creative
-- Projects already generated by Forge are intentionally preserved as ordinary
-- editable drafts.
delete from public.sol_operator_runs
where recipe_key = 'forge_carousel_stage';

delete from public.sol_operator_proposals
where recipe_key = 'forge_carousel_stage';

alter table public.sol_operator_proposals
  drop constraint if exists sol_operator_proposals_recipe_key_check;
alter table public.sol_operator_proposals
  add constraint sol_operator_proposals_recipe_key_check
  check (recipe_key in (
    'audio_to_youtube',
    'carousel_topic_pack',
    'journey_automation_draft'
  ));

alter table public.sol_operator_runs
  drop constraint if exists sol_operator_runs_recipe_key_check;
alter table public.sol_operator_runs
  add constraint sol_operator_runs_recipe_key_check
  check (recipe_key in (
    'audio_to_youtube',
    'carousel_topic_pack',
    'journey_automation_draft'
  ));

commit;
