"use client";
import { useEffect,useState } from "react";
import { MessageCircle,BarChart3,ThumbsUp } from "lucide-react";
type Question={id:string;body:string;display_name?:string|null;anonymous_to_audience:boolean;status:string;vote_count:number};type Option={id:string;label:string;sort_order:number};type Response={option_id:string};type Poll={id:string;question:string;status:string;show_results:boolean;live_poll_options:Option[];live_poll_responses:Response[]};
export default function LiveAudience({episodeId,title,youtubeUrl}:{episodeId:string;title:string;youtubeUrl?:string|null}){const [data,setData]=useState<{questions:Question[];polls:Poll[]}>({questions:[],polls:[]});const [needsLogin,setNeedsLogin]=useState(false);const [body,setBody]=useState("");const [anonymous,setAnonymous]=useState(false);const [message,setMessage]=useState("");
 async function load(){const r=await fetch(`/api/live/${episodeId}`,{cache:"no-store"});const p=await r.json();if(r.status===401){setNeedsLogin(true);return;}if(r.ok){setNeedsLogin(false);setData(p.audience??{questions:[],polls:[]});}}useEffect(()=>{void load();const id=setInterval(()=>void load(),3000);return()=>clearInterval(id);},[episodeId]);
 async function action(payload:Record<string,unknown>){setMessage("");const r=await fetch(`/api/live/${episodeId}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const p=await r.json();if(r.status===401){setNeedsLogin(true);setMessage(p.error);return false;}if(!r.ok){setMessage(p.error??"Unable to submit");return false;}await load();return true;}
 async function submit(e:React.FormEvent){e.preventDefault();if(await action({type:"question.submit",body,anonymous})){setBody("");setMessage("Question submitted for review.");}}
 const questions=data.questions.filter(q=>["approved","queued","live","answered"].includes(q.status)).sort((a,b)=>b.vote_count-a.vote_count);const polls=data.polls.filter(p=>p.status==="open"||p.status==="closed");
 return <main className="ag-live-page"><header><span>AG LIVE</span><h1>{title}</h1><p>Join the conversation while the episode is live.</p></header>{youtubeUrl?<div className="ag-live-video"><iframe src={youtubeUrl.replace("watch?v=","embed/")} title={title} allowFullScreen/></div>:<div className="ag-live-video ag-live-waiting">LIVE VIDEO WILL APPEAR HERE</div>}
 <div className="ag-live-columns"><section><div className="ag-live-section-title"><MessageCircle size={17}/><h2>Questions</h2></div>{needsLogin?<div className="ag-live-login">Sign in with your Apostolic Guide account to ask, vote, and participate in polls.<a href={`/login?next=/live/${episodeId}`}>SIGN IN</a></div>:<form onSubmit={submit}><textarea value={body} onChange={e=>setBody(e.target.value)} maxLength={1000} placeholder="What would you like discussed?"/><label><input type="checkbox" checked={anonymous} onChange={e=>setAnonymous(e.target.checked)}/> Show as anonymous</label><button disabled={!body.trim()}>SUBMIT QUESTION</button></form>}{message?<p className="ag-live-message">{message}</p>:null}<div className="ag-live-question-list">{questions.map(q=><article key={q.id}><div><p>{q.body}</p><small>{q.anonymous_to_audience?"Anonymous":q.display_name||"AG member"}</small></div><button onClick={()=>void action({type:"question.vote",questionId:q.id})}><ThumbsUp size={14}/>{q.vote_count}</button></article>)}</div></section>
 <section><div className="ag-live-section-title"><BarChart3 size={17}/><h2>Live Polls</h2></div>{polls.length===0?<div className="ag-live-empty">No poll is open right now.</div>:polls.map(p=>{const total=p.live_poll_responses?.length??0;return <article className="ag-live-poll" key={p.id}><span>{p.status==="open"?"OPEN NOW":"CLOSED"}</span><h3>{p.question}</h3>{[...(p.live_poll_options??[])].sort((a,b)=>a.sort_order-b.sort_order).map(o=>{const count=(p.live_poll_responses??[]).filter(r=>r.option_id===o.id).length;const pct=total?Math.round(count/total*100):0;return <button key={o.id} disabled={p.status!=="open"} onClick={()=>void action({type:"poll.answer",pollId:p.id,optionId:o.id})}><strong>{o.label}</strong>{p.show_results||p.status==="closed"?<em>{pct}%</em>:null}</button>})}<small>{total} response{total===1?"":"s"}</small></article>})}</section></div></main>;
}
