"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowRight, BarChart3, Check, FileText, Film, Headphones, Loader2, Plus, Save, Send, ShieldCheck, Sparkles, Target } from "lucide-react";
import { useRouter } from "next/navigation";
import { EPISODE_FORMATS, episodeFormatLabel, type EpisodeFormat, type EpisodeReview, type EpisodeSpeaker } from "@/video-producer-episode-script";
import { episodeGrowthPlanMatchesSource, episodeGrowthSourceFingerprint, parseEpisodeGrowthPlan, parseGrowthLearning, selectedEpisodeThumbnail, selectedEpisodeTitle, type YoutubePerformanceSnapshot } from "@/video-producer-growth";

type Stage = "package" | "script" | "audio" | "video" | "publish" | "learn";
type Pathway = { slug: string; title: string };
type Episode = {
  id: string; title: string; premise: string; primary_pathway_slug: string; supporting_pathway_slugs: string[];
  format: EpisodeFormat; speakers: EpisodeSpeaker[]; script_text: string; growth_plan: unknown; growth_learning: unknown;
  growth_metrics: { latest?: YoutubePerformanceSnapshot } | null; theology_review: (EpisodeReview & { growthContentRevision?: string }) | null;
  status: "draft" | "needs_review" | "approved" | "exported"; exported_project_id: string | null; audio_url: string | null;
  audio_generated_at: string | null; audio_voice_map: Record<string, string> | null;
};
type LoadData = { episodes: Episode[]; pathways: Pathway[] };
type Metrics = { impressions: string; views: string; clickThroughRate: string; averageViewDurationSeconds: string; averagePercentageViewed: string; first30SecondRetention: string; subscribersGained: string };

const STAGES: Array<{ id: Stage; label: string; icon: typeof FileText }> = [
  { id: "package", label: "Package", icon: Target }, { id: "script", label: "Script", icon: FileText }, { id: "audio", label: "Audio", icon: Headphones },
  { id: "video", label: "Video", icon: Film }, { id: "publish", label: "Publish", icon: Send }, { id: "learn", label: "Learn", icon: BarChart3 }
];
const blankMetrics: Metrics = { impressions: "", views: "", clickThroughRate: "", averageViewDurationSeconds: "", averagePercentageViewed: "", first30SecondRetention: "", subscribersGained: "0" };
const speakersFor = (format: EpisodeFormat): EpisodeSpeaker[] => format === "solo" ? [{ name: "Cedar", role: "host" }] : format === "dialogue" ? [{ name: "Cedar", role: "host" }, { name: "Guest", role: "conversation partner" }] : [{ name: "Cedar", role: "host" }, { name: "Guest 1", role: "conversation partner" }, { name: "Guest 2", role: "conversation partner" }];
async function api<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, { ...init, cache: "no-store", headers: { "content-type": "application/json", ...(init?.headers ?? {}) } }); const data = await response.json().catch(() => ({})) as T & { error?: string }; if (!response.ok) throw new Error(data.error || `Request failed (${response.status}).`); return data; }
function metricsFor(episode: Episode | null): Metrics { const value = episode?.growth_metrics?.latest; return value ? { impressions: String(value.impressions), views: String(value.views), clickThroughRate: String(value.clickThroughRate), averageViewDurationSeconds: String(value.averageViewDurationSeconds), averagePercentageViewed: String(value.averagePercentageViewed), first30SecondRetention: value.first30SecondRetention == null ? "" : String(value.first30SecondRetention), subscribersGained: String(value.subscribersGained) } : { ...blankMetrics }; }

export function EpisodeStudioLane() {
  const router = useRouter();
  const [stage, setStage] = useState<Stage>("package");
  const [episodes, setEpisodes] = useState<Episode[]>([]); const [pathways, setPathways] = useState<Pathway[]>([]); const [activeId, setActiveId] = useState<string | null>(null); const [draft, setDraft] = useState<Episode | null>(null);
  const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [dirty, setDirty] = useState(false); const [metrics, setMetrics] = useState<Metrics>({ ...blankMetrics });
  const [newOpen, setNewOpen] = useState(false); const [newTitle, setNewTitle] = useState(""); const [newPremise, setNewPremise] = useState(""); const [newPrimary, setNewPrimary] = useState(""); const [newFormat, setNewFormat] = useState<EpisodeFormat>("solo");

  const load = useCallback(async () => { try { const data = await api<LoadData>("/api/admin/video-producer/episodes"); setEpisodes(data.episodes ?? []); setPathways(data.pathways ?? []); setActiveId((value) => value || data.episodes?.[0]?.id || null); setNewPrimary((value) => value || data.pathways?.[0]?.slug || ""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Episodes could not be loaded."); } }, []);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { const selected = episodes.find((episode) => episode.id === activeId) ?? null; setDraft(selected ? structuredClone(selected) : null); setMetrics(metricsFor(selected)); setDirty(false); }, [activeId, episodes]);

  const plan = parseEpisodeGrowthPlan(draft?.growth_plan); const learning = parseGrowthLearning(draft?.growth_learning);
  const fingerprint = useMemo(() => draft ? episodeGrowthSourceFingerprint({ workingTitle: draft.title, premise: draft.premise, primaryPathwaySlug: draft.primary_pathway_slug, supportingPathwaySlugs: draft.supporting_pathway_slugs, format: draft.format, speakers: draft.speakers }) : "", [draft]);
  const packageReady = Boolean(plan && episodeGrowthPlanMatchesSource(plan, fingerprint)); const reviewReady = Boolean(plan && draft?.theology_review?.growthContentRevision === plan.contentRevision && draft.theology_review.verdict === "passed");
  const scriptReady = Boolean(draft && packageReady && reviewReady && ["approved", "exported"].includes(draft.status)); const audioReady = Boolean(scriptReady && draft?.audio_url); const videoReady = Boolean(audioReady && draft?.exported_project_id);
  const selectedTitle = plan ? selectedEpisodeTitle(plan) : ""; const selectedThumbnail = plan ? selectedEpisodeThumbnail(plan) : null;

  function mutate(patch: Partial<Episode>) { setDraft((value) => value ? { ...value, ...patch } : value); setDirty(true); }
  function sync(episode: Episode) { setEpisodes((items) => items.map((item) => item.id === episode.id ? episode : item)); setDraft(episode); setMetrics(metricsFor(episode)); setDirty(false); }
  async function save() { if (!draft || !dirty) return true; setBusy("save"); try { const data = await api<{ episode: Episode }>(`/api/admin/video-producer/episodes/${draft.id}`, { method: "PATCH", body: JSON.stringify({ title: draft.title, premise: draft.premise, primaryPathwaySlug: draft.primary_pathway_slug, supportingPathwaySlugs: draft.supporting_pathway_slugs, format: draft.format, speakers: draft.speakers, scriptText: draft.script_text }) }); sync(data.episode); return true; } catch (cause) { setError(cause instanceof Error ? cause.message : "Save failed."); return false; } finally { setBusy(""); } }
  async function action(name: string, url: string, body?: unknown) { if (!draft) return null; if (dirty && !(await save())) return null; setBusy(name); setError(""); try { const data = await api<{ episode: Episode; projectId?: string; learning?: unknown }>(url, { method: "POST", body: body === undefined ? undefined : JSON.stringify(body) }); if (data.episode) sync(data.episode); return data; } catch (cause) { setError(cause instanceof Error ? cause.message : `${name} failed.`); return null; } finally { setBusy(""); } }
  async function createEpisode() { if (!newTitle.trim() || !newPremise.trim() || !newPrimary) return; setBusy("create"); try { const data = await api<{ episode: Episode }>("/api/admin/video-producer/episodes", { method: "POST", body: JSON.stringify({ title: newTitle, premise: newPremise, primaryPathwaySlug: newPrimary, supportingPathwaySlugs: [], format: newFormat, speakers: speakersFor(newFormat) }) }); setEpisodes((items) => [data.episode, ...items]); setActiveId(data.episode.id); setNewOpen(false); setStage("package"); setMessage("Episode created. Build the package before writing the script."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Episode could not be created."); } finally { setBusy(""); } }
  async function choose(selection: { titleIndex?: number; thumbnailIndex?: number }) { if (!draft) return; setBusy("choose"); try { const response = await fetch(`/api/admin/video-producer/episodes/${draft.id}/package`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(selection) }); const data = await response.json() as { episode?: Episode; error?: string }; if (!response.ok || !data.episode) throw new Error(data.error || "Selection failed."); sync(data.episode); } catch (cause) { setError(cause instanceof Error ? cause.message : "Selection failed."); } finally { setBusy(""); } }
  async function savePerformance() { if (!draft) return; const payload = { impressions: Number(metrics.impressions), views: Number(metrics.views), clickThroughRate: Number(metrics.clickThroughRate), averageViewDurationSeconds: Number(metrics.averageViewDurationSeconds), averagePercentageViewed: Number(metrics.averagePercentageViewed), first30SecondRetention: metrics.first30SecondRetention ? Number(metrics.first30SecondRetention) : null, subscribersGained: metrics.subscribersGained ? Number(metrics.subscribersGained) : 0, shortsViews: null, shortsAveragePercentageViewed: null }; if (Object.values(payload).some((value) => typeof value === "number" && !Number.isFinite(value))) return setError("Enter valid performance numbers."); const data = await action("learn", `/api/admin/video-producer/episodes/${draft.id}/performance`, payload); if (data) setMessage("Performance saved. The next experiment is ready when the baseline is strong enough."); }

  return <main className="episode-lane-page"><div className="episode-lane-shell">
    <header className="episode-lane-hero"><div><span>Apostolic Guide Media</span><h1>Episode Studio</h1><p>Idea → Package → Script → Produce → Publish → Learn. Teach like Apostolic Guide. Package and pace like YouTube.</p></div><button className="button primary" onClick={() => setNewOpen((value) => !value)}><Plus size={15}/> New episode</button></header>
    <nav className="episode-lane-steps" style={{ gridTemplateColumns: "repeat(6,minmax(82px,1fr))" }}>{STAGES.map((item, index) => { const Icon = item.icon; const complete = item.id === "package" ? packageReady : item.id === "script" ? scriptReady : item.id === "audio" ? audioReady : item.id === "video" || item.id === "publish" ? videoReady : Boolean(draft?.growth_metrics?.latest); return <button key={item.id} type="button" data-active={stage === item.id} data-complete={complete} onClick={() => setStage(item.id)}><span>{complete ? <Check size={13}/> : index + 1}</span><Icon size={15}/><strong>{item.label}</strong></button>; })}</nav>
    {newOpen ? <section className="episode-lane-new"><h2>What do you want to talk about?</h2><div className="episode-lane-new-grid"><label>Working title<input value={newTitle} onChange={(event) => setNewTitle(event.target.value)}/></label><label>Primary Pathway<select value={newPrimary} onChange={(event) => setNewPrimary(event.target.value)}>{pathways.map((pathway) => <option key={pathway.slug} value={pathway.slug}>{pathway.title}</option>)}</select></label><label className="wide">Your thought<textarea rows={4} value={newPremise} onChange={(event) => setNewPremise(event.target.value)}/></label><label>Format<select value={newFormat} onChange={(event) => setNewFormat(event.target.value as EpisodeFormat)}>{EPISODE_FORMATS.map((format) => <option key={format} value={format}>{episodeFormatLabel(format)}</option>)}</select></label></div><button className="button primary" disabled={busy === "create"} onClick={() => void createEpisode()}>{busy === "create" ? <Loader2 className="spin" size={14}/> : <ArrowRight size={14}/>} Create and package</button></section> : null}
    {error ? <div className="admin-notice episode-error">{error}</div> : null}{message ? <div className="episode-lane-message">{message}</div> : null}
    <div className="episode-lane-workspace"><aside className="episode-lane-library"><div className="episode-lane-library-head"><strong>Episodes</strong><span>{episodes.length}</span></div>{episodes.map((episode) => <button key={episode.id} type="button" data-active={episode.id === activeId} onClick={() => setActiveId(episode.id)}><strong>{episode.title}</strong><span>{episodeFormatLabel(episode.format)}</span></button>)}</aside>
    <section className="episode-lane-panel">{!draft ? <div className="episode-lane-zero"><FileText size={28}/><strong>No episode selected</strong></div> : <>
      <div className="episode-lane-context"><div><span>{draft.primary_pathway_slug}</span><h2>{selectedTitle || draft.title}</h2><p>{episodeFormatLabel(draft.format)}</p></div><button className="button small" disabled={!dirty || Boolean(busy)} onClick={() => void save()}><Save size={13}/> Save</button></div>
      {stage === "package" ? <div className="episode-lane-stage"><div className="episode-lane-stage-head"><span>01 · Package</span><h3>Decide why they click before writing what you say.</h3></div><div className="episode-lane-form-grid"><label>Working title<input value={draft.title} onChange={(event) => mutate({ title: event.target.value })}/></label><label>Primary Pathway<select value={draft.primary_pathway_slug} onChange={(event) => mutate({ primary_pathway_slug: event.target.value })}>{pathways.map((pathway) => <option key={pathway.slug} value={pathway.slug}>{pathway.title}</option>)}</select></label><label className="wide">Thought / premise<textarea rows={4} value={draft.premise} onChange={(event) => mutate({ premise: event.target.value })}/></label></div><button className="button primary" disabled={Boolean(busy)} onClick={() => void action("package", `/api/admin/video-producer/episodes/${draft.id}/package`).then((data) => data && setMessage("Package built. Choose the title and thumbnail, then write the script."))}><Sparkles size={14}/> {plan ? "Rebuild YouTube package" : "Build YouTube package"}</button>{plan ? <div className="episode-lane-package" style={{ display: "grid", gap: 14 }}><section><strong>Title candidates</strong>{plan.packaging.titleCandidates.map((title, index) => <button className="button" key={title} data-selected={index === plan.packaging.selectedTitleIndex} disabled={!packageReady} onClick={() => void choose({ titleIndex: index })}>{title}</button>)}</section><section><strong>Thumbnail concepts</strong>{plan.packaging.thumbnailConcepts.map((thumb, index) => <button className="button" key={thumb.copy} data-selected={index === plan.packaging.selectedThumbnailIndex} disabled={!packageReady} onClick={() => void choose({ thumbnailIndex: index })}>{thumb.copy} · {thumb.mechanism}</button>)}</section><div className="episode-lane-review"><p><b>Promise:</b> {plan.audience.promise}</p><p><b>Hook:</b> {plan.retention.hook}</p><p><b>Payoff:</b> {plan.retention.payoff}</p></div><button className="button primary" disabled={!packageReady} onClick={() => setStage("script")}>Continue to Script <ArrowRight size={14}/></button></div> : null}</div> : null}
      {stage === "script" ? <div className="episode-lane-stage"><div className="episode-lane-stage-head"><span>02 · Script</span><h3>Write the episode that fulfills the click.</h3></div>{!packageReady ? <div className="episode-lane-blocked"><Target size={22}/><strong>Build the current package first.</strong></div> : <><div className="episode-lane-review"><strong>{selectedTitle}</strong><p>Thumbnail: {selectedThumbnail?.copy}</p></div><button className="button primary" disabled={Boolean(busy)} onClick={() => void action("generate", `/api/admin/video-producer/episodes/${draft.id}/generate`)}><Sparkles size={14}/> Generate script</button><label className="episode-lane-script">Episode script<textarea rows={24} value={draft.script_text} onChange={(event) => mutate({ script_text: event.target.value })}/></label>{draft.theology_review ? <div className="episode-lane-review" data-verdict={draft.theology_review.verdict}><ShieldCheck size={17}/><strong>{draft.theology_review.verdict === "passed" ? "Theology + package check passed" : "Review required"}</strong><p>{draft.theology_review.summary}</p></div> : null}<div className="episode-lane-actions"><button className="button" disabled={!draft.script_text.trim() || Boolean(busy)} onClick={() => void action("review", `/api/admin/video-producer/episodes/${draft.id}/review`, { approve: false })}><ShieldCheck size={14}/> Theology + Package Check</button><button className="button" disabled={!reviewReady || scriptReady || Boolean(busy)} onClick={() => void action("approve", `/api/admin/video-producer/episodes/${draft.id}/review`, { approve: true })}><Check size={14}/> Approve script</button><button className="button primary" disabled={!scriptReady} onClick={() => setStage("audio")}>Continue to Audio <ArrowRight size={14}/></button></div></>}</div> : null}
      {stage === "audio" ? <div className="episode-lane-stage"><div className="episode-lane-stage-head"><span>03 · Audio</span><h3>Make the approved script audible.</h3></div>{!scriptReady ? <div className="episode-lane-blocked"><ShieldCheck size={22}/><strong>Approve the current script first.</strong></div> : <><button className="button primary" disabled={Boolean(busy)} onClick={() => void action("audio", `/api/admin/episode-studio/${draft.id}/audio`)}><Headphones size={14}/> {audioReady ? "Regenerate audio" : "Generate audio"}</button>{draft.audio_url ? <audio controls src={draft.audio_url}/> : null}<button className="button" disabled={!audioReady} onClick={() => setStage("video")}>Continue to Video <ArrowRight size={14}/></button></>}</div> : null}
      {stage === "video" ? <div className="episode-lane-stage"><div className="episode-lane-stage-head"><span>04 · Video</span><h3>Produce from the same growth plan.</h3><p>Video Producer receives title, thumbnail, retention, B-roll, graphics, camera resets, and Shorts direction.</p></div>{videoReady ? <button className="button primary" onClick={() => router.push(`/admin/video-producer/${draft.exported_project_id}/source`)}>Open video project</button> : <button className="button primary" disabled={!audioReady || Boolean(busy)} onClick={() => void action("video", `/api/admin/video-producer/episodes/${draft.id}/export`).then((data) => data?.projectId && void load())}><Film size={14}/> Create video project</button>}<button className="button" disabled={!videoReady} onClick={() => setStage("publish")}>Continue to Publish <ArrowRight size={14}/></button></div> : null}
      {stage === "publish" ? <div className="episode-lane-stage"><div className="episode-lane-stage-head"><span>05 · Publish</span><h3>Publish the package you actually produced.</h3></div><div className="episode-lane-publish-card"><strong>{selectedTitle || draft.title}</strong><p>Thumbnail: {selectedThumbnail?.copy || "Not selected"}</p><button className="button primary" disabled={!videoReady} onClick={() => router.push(`/admin/publishing?view=video&projectId=${encodeURIComponent(draft.exported_project_id || "")}&pathwaySlug=${encodeURIComponent(draft.primary_pathway_slug)}`)}><Send size={15}/> Open in Publishing</button><button className="button" onClick={() => setStage("learn")}>Record performance later <ArrowRight size={14}/></button></div></div> : null}
      {stage === "learn" ? <div className="episode-lane-stage"><div className="episode-lane-stage-head"><span>06 · Learn</span><h3>Teach the system what actually worked.</h3></div><div className="episode-lane-form-grid">{(["impressions", "views", "clickThroughRate", "averageViewDurationSeconds", "averagePercentageViewed", "first30SecondRetention", "subscribersGained"] as const).map((key) => <label key={key}>{key}<input value={metrics[key]} onChange={(event) => setMetrics((value) => ({ ...value, [key]: event.target.value }))}/></label>)}</div><button className="button primary" disabled={Boolean(busy)} onClick={() => void savePerformance()}><BarChart3 size={14}/> Save performance + learn</button>{learning ? <div className="episode-lane-review"><strong>{learning.state === "collecting_baseline" ? "Collecting baseline" : `Package ${learning.packaging} · Retention ${learning.retention}`}</strong>{learning.observations.map((item) => <p key={item}>{item}</p>)}<p><b>Next experiment:</b> {learning.nextExperiment}</p></div> : null}</div> : null}
    </>}</section></div>
  </div></main>;
}
