"use client";
import { useState } from "react";
import { Copy, Globe2, Loader2, RefreshCw, Send } from "lucide-react";

type Item={headline:string;eventSummary:string;sourceTitle:string;sourceUrl:string;draft:string;whyAppropriate:string};
export function ThreadsPrayerNews(){const[focus,setFocus]=useState("major natural disasters and humanitarian emergencies where a brief non-political prayerful response would be appropriate");const[items,setItems]=useState<Item[]>([]);const[busy,setBusy]=useState(false);const[sending,setSending]=useState<string>();const[message,setMessage]=useState("Source-reviewed prayer drafts only. No political commentary or speculation.");
async function scan(){setBusy(true);setMessage("Scanning recent humanitarian events…");try{const r=await fetch("/api/admin/threads-studio/news",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({focus,count:3})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Scan failed.");setItems(Array.isArray(d.items)?d.items:[]);setMessage(d.items?.length?"Review each source before sending a prayer draft to Publishing.":"Nothing strong enough to recommend right now.");}catch(e){setMessage(e instanceof Error?e.message:"Scan failed.");}finally{setBusy(false);}}
function copy(value:string){void navigator.clipboard?.writeText(value);setMessage("Draft copied. Review the source before publishing.");}
async function send(item:Item){setSending(item.sourceUrl);setMessage("Saving reviewed prayer draft…");try{const r=await fetch("/api/admin/threads-studio/ready",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({allowWarnings:false,items:[{body:item.draft,category:"prayer-news",doctrineStatus:"pass",sourceTitle:item.sourceTitle,sourceUrl:item.sourceUrl,sourceSummary:item.eventSummary,mirrorToX:false}]})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not send the prayer draft to Publishing.");const readyId=Array.isArray(d.posts)&&d.posts[0]?.id?String(d.posts[0].id):"";if(!readyId)throw new Error("Prayer draft was saved, but its publishing ID was not returned.");setMessage("Prayer draft is ready in Publishing.");window.location.assign(`/admin/publishing?view=threads&threadId=${encodeURIComponent(readyId)}`);}catch(e){setMessage(e instanceof Error?e.message:"Could not send the prayer draft to Publishing.");setSending(undefined);}}
return <div className="threads-panel"><div className="threads-panel-title"><div><strong>Prayer + humanitarian news</strong><span>Compassion first. Source required.</span></div><Globe2 size={18}/></div><label><span>Scan focus</span><textarea rows={3} value={focus} onChange={e=>setFocus(e.target.value)}/></label><button className="button" onClick={()=>void scan()} disabled={busy}>{busy?<Loader2 className="spin" size={15}/>:<RefreshCw size={15}/>} Scan recent events</button><p className="threads-status">{message}</p><div className="threads-news-list">{items.map(item=><article key={item.sourceUrl}><strong>{item.headline}</strong><p>{item.eventSummary}</p><blockquote>{item.draft}</blockquote><small>{item.sourceTitle}</small><div><a href={item.sourceUrl} target="_blank" rel="noreferrer">Review source</a><button className="button small" onClick={()=>copy(item.draft)}><Copy size={13}/> Copy draft</button><button className="button small" disabled={Boolean(sending)} onClick={()=>void send(item)}>{sending===item.sourceUrl?<Loader2 className="spin" size={13}/>:<Send size={13}/>} Reviewed → Publishing</button></div></article>)}</div></div>}
