"use client";
import { useMemo, useState } from "react";
import { CalendarDays, Loader2, ShieldCheck, Sparkles } from "lucide-react";

type Draft={id?:string;category:string;body:string;selected:boolean;doctrineStatus?:"pass"|"warning"|"blocked";doctrineNotes?:string};
function monday(){const n=new Date(),d=n.getDay(),x=d===0?-6:1-d,m=new Date(n);m.setDate(n.getDate()+x);return `${m.getFullYear()}-${String(m.getMonth()+1).padStart(2,"0")}-${String(m.getDate()).padStart(2,"0")}`;}
function slots(start:string,count:number){const base=new Date(`${start}T00:00:00`),out:string[]=[];let day=0;while(out.length<count){for(const hour of [9,16]){if(out.length>=count)break;const v=new Date(base);v.setDate(base.getDate()+day);v.setHours(hour,hour===16?45:15,0,0);out.push(v.toISOString());}day++;}return out;}
export function ThreadsWeeklyPlanner(){const[weekStart,setWeekStart]=useState(monday());const[topic,setTopic]=useState("Oneness theology, Jesus Christ, Scripture, and practical Apostolic Bible study");const[count,setCount]=useState(10);const[batchId,setBatchId]=useState<string>();const[drafts,setDrafts]=useState<Draft[]>([]);const[busy,setBusy]=useState<string>();const[message,setMessage]=useState("Generate, review, approve, then place the week on the calendar.");const[allowWarnings,setAllowWarnings]=useState(false);const selected=useMemo(()=>drafts.filter(x=>x.selected),[drafts]);
async function generate(){setBusy("generate");try{const r=await fetch("/api/admin/threads-studio/generate-week",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({weekStart,topic,count})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Generation failed.");setBatchId(d.batch?.id);setDrafts((d.posts?.length?d.posts:d.plan?.posts||[]).map((p:any)=>({id:p.id,category:p.category,body:p.body,selected:true})));setMessage("Drafts ready. Run theology check.");}catch(e){setMessage(e instanceof Error?e.message:"Generation failed.");}finally{setBusy(undefined);}}
async function check(){setBusy("check");try{const r=await fetch("/api/admin/threads-studio/check",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({batchId,posts:drafts.map(x=>({id:x.id,body:x.body,category:x.category}))})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Review failed.");setDrafts(cur=>cur.map((x,i)=>{const y=d.review?.posts?.find((p:any)=>p.index===i);return y?{...x,doctrineStatus:y.status,doctrineNotes:y.notes}:x;}));setMessage(d.review?.summary||"Review complete.");}catch(e){setMessage(e instanceof Error?e.message:"Review failed.");}finally{setBusy(undefined);}}
async function queue(){if(selected.some(x=>!x.doctrineStatus)){setMessage("Review every selected post first.");return;}if(selected.some(x=>x.doctrineStatus==="blocked")){setMessage("Blocked posts cannot be queued.");return;}if(selected.some(x=>x.doctrineStatus==="warning")&&!allowWarnings){setMessage("Resolve warnings or explicitly approve them.");return;}setBusy("queue");try{const times=slots(weekStart,selected.length);const r=await fetch("/api/admin/threads-studio/queue",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({batchId,allowWarnings,items:selected.map((x,i)=>({id:x.id,body:x.body,category:x.category,scheduledFor:times[i],doctrineStatus:x.doctrineStatus,mirrorToX:false}))})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Queue failed.");setMessage(`${selected.length} Threads posts added to the calendar.`);}catch(e){setMessage(e instanceof Error?e.message:"Queue failed.");}finally{setBusy(undefined);}}
return <div className="threads-panel"><div className="threads-panel-title"><div><strong>Weekly theology batch</strong><span>Serious, witty, Scripture-first.</span></div><Sparkles size={18}/></div><label><span>Week starts</span><input type="date" value={weekStart} onChange={e=>setWeekStart(e.target.value)}/></label><label><span>Focus</span><textarea rows={3} value={topic} onChange={e=>setTopic(e.target.value)}/></label><label><span>Posts</span><select value={count} onChange={e=>setCount(Number(e.target.value))}><option value={7}>7</option><option value={10}>10</option><option value={12}>12</option><option value={14}>14</option></select></label><button className="button button-primary" disabled={Boolean(busy)} onClick={()=>void generate()}>{busy==="generate"?<Loader2 className="spin" size={15}/>:<Sparkles size={15}/>} Generate week</button>{drafts.length?<><div className="threads-review-actions"><button className="button" onClick={()=>void check()} disabled={Boolean(busy)}><ShieldCheck size={15}/> Theology check</button><label><input type="checkbox" checked={allowWarnings} onChange={e=>setAllowWarnings(e.target.checked)}/> allow reviewed warnings</label></div><div className="threads-draft-list">{drafts.map((x,i)=><article key={x.id||i} className={`threads-draft is-${x.doctrineStatus||"unchecked"}`}><input type="checkbox" checked={x.selected} onChange={e=>setDrafts(cur=>cur.map((v,j)=>j===i?{...v,selected:e.target.checked}:v))}/><div><b>{x.category}</b><textarea rows={3} value={x.body} onChange={e=>setDrafts(cur=>cur.map((v,j)=>j===i?{...v,body:e.target.value,doctrineStatus:undefined,doctrineNotes:undefined}:v))}/>{x.doctrineStatus?<small>{x.doctrineStatus}: {x.doctrineNotes||"reviewed"}</small>:null}</div></article>)}</div><button className="button button-primary" onClick={()=>void queue()} disabled={Boolean(busy)}>{busy==="queue"?<Loader2 className="spin" size={15}/>:<CalendarDays size={15}/>} Approve + add to calendar</button></>:null}<p className="threads-status">{message}</p></div>}
