create table if not exists public.custom_segments (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 1 and 120),
  description text,
  match_mode text not null default 'all' check (match_mode in ('all','any')),
  rules jsonb not null default '[]'::jsonb,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists custom_segments_updated_at_idx on public.custom_segments(updated_at desc);
alter table public.custom_segments enable row level security;
revoke all on public.custom_segments from anon, authenticated;
grant all on public.custom_segments to service_role;

create table if not exists public.studio_notifications (
  id bigint generated by default as identity primary key,
  type text not null,
  severity text not null default 'info' check (severity in ('info','success','warning','error')),
  title text not null,
  detail text,
  href text,
  person_id uuid references public.people(id) on delete set null,
  entity_type text,
  entity_id text,
  dedupe_key text unique,
  read_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists studio_notifications_unread_idx on public.studio_notifications(read_at, created_at desc);
create index if not exists studio_notifications_person_idx on public.studio_notifications(person_id, created_at desc);
alter table public.studio_notifications enable row level security;
revoke all on public.studio_notifications from anon, authenticated;
grant all on public.studio_notifications to service_role;
