begin;
create table if not exists public.studio_people(id uuid primary key default gen_random_uuid(),name text not null,title text,organization text,email text,image_url text,notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.studio_episode_guests(id uuid primary key default gen_random_uuid(),episode_id uuid not null references public.studio_episodes(id) on delete cascade,person_id uuid references public.studio_people(id) on delete set null,display_name text not null,state text not null default 'invited' check(state in('invited','connecting','green_room','private','queued','live','disconnected','ended')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.studio_guest_invites(id uuid primary key default gen_random_uuid(),episode_id uuid not null references public.studio_episodes(id) on delete cascade,guest_id uuid not null references public.studio_episode_guests(id) on delete cascade,token_hash text not null unique,status text not null default 'active' check(status in('active','used','revoked','expired')),expires_at timestamptz,created_at timestamptz not null default now());
create index if not exists studio_episode_guests_episode_idx on public.studio_episode_guests(episode_id,state);create index if not exists studio_guest_invites_guest_idx on public.studio_guest_invites(guest_id,status);
create trigger touch_studio_people before update on public.studio_people for each row execute function public.touch_updated_at();create trigger touch_studio_episode_guests before update on public.studio_episode_guests for each row execute function public.touch_updated_at();
alter table public.studio_people enable row level security;alter table public.studio_episode_guests enable row level security;alter table public.studio_guest_invites enable row level security;
create policy "admins manage studio people" on public.studio_people for all to authenticated using ((select auth.jwt()->'app_metadata'->>'role')='admin') with check ((select auth.jwt()->'app_metadata'->>'role')='admin');create policy "admins manage studio guests" on public.studio_episode_guests for all to authenticated using ((select auth.jwt()->'app_metadata'->>'role')='admin') with check ((select auth.jwt()->'app_metadata'->>'role')='admin');create policy "admins manage guest invites" on public.studio_guest_invites for all to authenticated using ((select auth.jwt()->'app_metadata'->>'role')='admin') with check ((select auth.jwt()->'app_metadata'->>'role')='admin');
commit;
