"use client";
import { useEffect,useState } from "react";
type Q={id:string;body:string;display_name?:string;anonymous_to_audience:boolean;status:string;vote_count:number};type P={id:string;question:string;status:string;show_results:boolean;live_poll_responses?:unknown[]};
export function AudiencePanel({episodeId}:{episodeId:string}){const [questions,setQuestions]=useState<Q[]>([]);const [polls,setPolls]=useState<P[]>([]);const [pollQuestion,setPollQuestion]=useState("");const [options,setOptions]=useState(["Yes","No"]);const [error,setError]=useState("");
 async function load(){const r=await fetch(`/api/studio/episodes/${episodeId}/audience`,{cache:"no-store"});if(r.ok){const p=await r.json();setQuestions(p.questions??[]);setPolls(p.polls??[]);}}useEffect(()=>{void load();const id=setInterval(()=>void load(),3000);return()=>clearInterval(id);},[episodeId]);
 async function act(payload:Record<string,unknown>){setError("");const r=await fetch(`/api/studio/episodes/${episodeId}/audience`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const p=await r.json();if(!r.ok){setError(p.error??"Audience action failed");return;}await load();}
 async function create(e:React.FormEvent){e.preventDefault();await act({type:"poll.create",question:pollQuestion,options:options.filter(Boolean)});setPollQuestion("");}
 return <section className="ag-studio-panel ag-audience-panel"><header><div><span className="ag-studio-eyebrow">AG Live</span><h2>Audience</h2></div><a href={`/live/${episodeId}`} target="_blank">VIEW LIVE PAGE</a></header>{error?<div className="ag-studio-error">{error}</div>:null}<div className="ag-audience-columns"><div><h3>QUESTIONS <span>{questions.filter(q=>!['answered','dismissed'].includes(q.status)).length}</span></h3>{questions.length===0?<p className="ag-studio-muted">Questions will appear here as people submit them.</p>:questions.sort((a,b)=>b.vote_count-a.vote_count).map(q=><article className="ag-audience-question" key={q.id}><p>{q.body}</p><small>{q.anonymous_to_audience?"Anonymous":q.display_name||"AG member"} • {q.vote_count} votes • {q.status}</small><div>{q.status==="submitted"?<button onClick={()=>void act({type:"question.status",questionId:q.id,status:"approved"})}>APPROVE</button>:null}<button onClick={()=>void act({type:"question.status",questionId:q.id,status:"queued"})}>QUEUE</button><button onClick={()=>void act({type:"question.status",questionId:q.id,status:"live"})}>LIVE</button><button onClick={()=>void act({type:"question.status",questionId:q.id,status:"answered"})}>ANSWERED</button><button onClick={()=>void act({type:"question.status",questionId:q.id,status:"dismissed"})}>DISMISS</button></div></article>)}</div><div><h3>POLLS <span>{polls.length}</span></h3><form className="ag-poll-builder" onSubmit={create}><input value={pollQuestion} onChange={e=>setPollQuestion(e.target.value)} placeholder="Poll question"/>{options.map((o,i)=><input key={i} value={o} onChange={e=>setOptions(v=>v.map((x,n)=>n===i?e.target.value:x))} placeholder={`Option ${i+1}`}/>)}<div><button type="button" onClick={()=>setOptions(v=>[...v,""])}>+ OPTION</button><button disabled={!pollQuestion.trim()||options.filter(Boolean).length<2}>CREATE POLL</button></div></form>{polls.map(p=><article className="ag-audience-poll" key={p.id}><strong>{p.question}</strong><small>{p.status} • {p.live_poll_responses?.length??0} responses</small><div><button onClick={()=>void act({type:"poll.state",pollId:p.id,status:p.status==="open"?"closed":"open"})}>{p.status==="open"?"CLOSE":"OPEN"}</button><button onClick={()=>void act({type:"poll.state",pollId:p.id,showResults:!p.show_results})}>{p.show_results?"HIDE RESULTS":"SHOW RESULTS"}</button></div></article>)}</div></div></section>;
}
