import Link from "next/link";
import { ArrowLeft, BookOpen, Radio } from "lucide-react";
import { CueControls } from "./cue-controls";
import { RunEditor } from "./run-editor";
import { SessionControls } from "./session-controls";
import { AudiencePanel } from "./audience-panel";

type CueRow={id:string;label:string;position:number;presenter_notes?:string|null};type EpisodeData={episode:{id:string;title:string;episode_type:string;access_mode:string;status:string};run:{id:string;name:string}|null;cues:CueRow[]};type Pathway={slug:string;title:string;summary:string;steps:Array<{title:string;reference:string;explanation:string}>};
export default function EpisodeWorkspace({data,pathway}:{data:EpisodeData;pathway:Pathway}){const existing=new Set(data.cues.map(c=>c.label));return <main className="ag-studio ag-studio-workspace"><header className="ag-studio-topbar"><Link href="/studio" className="ag-studio-back"><ArrowLeft size={17}/> Studio</Link><span className="ag-studio-status">{data.episode.status}</span></header><section className="ag-studio-hero"><div><span className="ag-studio-eyebrow">{data.episode.episode_type} • {data.episode.access_mode}</span><h1>{data.episode.title}</h1><p>Primary pathway: {pathway.title}</p></div>{data.run?<SessionControls episodeId={data.episode.id} runId={data.run.id}/>:null}</section><div className="ag-studio-grid"><section className="ag-studio-panel"><header><div><span className="ag-studio-eyebrow">Assets</span><h2>{pathway.title}</h2></div><BookOpen size={20}/></header><p className="ag-studio-muted">{pathway.summary}</p><div className="ag-studio-step-list">{pathway.steps.map((step,index)=><article key={`${step.reference}-${index}`}><span className="ag-studio-step-number">{String(index+1).padStart(2,"0")}</span><div><strong>{step.reference}</strong><span>{step.title}</span><p>{step.explanation}</p></div><CueControls episodeId={data.episode.id} pathwayId={pathway.slug} step={step} added={existing.has(step.reference)}/></article>)}</div></section><section className="ag-studio-panel"><header><div><span className="ag-studio-eyebrow">Production</span><h2>{data.run?.name??"Run of show"}</h2></div><Radio size={20}/></header>{data.run?<RunEditor runId={data.run.id} initialCues={data.cues}/>:<div className="ag-studio-placeholder">Create a run of show to begin.</div>}</section></div><AudiencePanel episodeId={data.episode.id}/></main>;}
