"use client";
import{useEffect,useState}from"react";import{Copy,Mail,MessageCircle,UserPlus,Users}from"lucide-react";
type Guest={id:string;display_name:string;state:string;studio_people?:{email?:string|null;title?:string|null;organization?:string|null}|null};type Msg={id:string;guest_id?:string|null;sender_role:string;body:string;created_at:string};
export function GuestPanel({episodeId}:{episodeId:string}){const[guests,setGuests]=useState<Guest[]>([]),[messages,setMessages]=useState<Msg[]>([]),[name,setName]=useState(""),[email,setEmail]=useState(""),[sendEmail,setSendEmail]=useState(true),[message,setMessage]=useState(""),[target,setTarget]=useState(""),[error,setError]=useState(""),[lastLink,setLastLink]=useState("");
 async function load(){const r=await fetch(`/api/studio/episodes/${episodeId}/guests`,{cache:"no-store"});if(r.ok){const p=await r.json();setGuests(p.guests??[]);setMessages(p.messages??[]);}}useEffect(()=>{void load();const id=setInterval(()=>void load(),2500);return()=>clearInterval(id);},[episodeId]);
 async function act(payload:Record<string,unknown>){setError("");const r=await fetch(`/api/studio/episodes/${episodeId}/guests`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const p=await r.json();if(!r.ok){setError(p.error??"Guest action failed");return null;}if(p.guestUrl)setLastLink(p.guestUrl);await load();return p;}
 async function invite(e:React.FormEvent){e.preventDefault();const p=await act({type:"invite",name,email,sendEmail:sendEmail&&Boolean(email)});if(p){setName("");setEmail("");}}
 async function sendMessage(e:React.FormEvent){e.preventDefault();if(!message.trim())return;const p=await act({type:"message",guestId:target||undefined,body:message});if(p)setMessage("");}
 return <section className="ag-studio-panel ag-guests-panel"><header><div><span className="ag-studio-eyebrow">Guests</span><h2>Green room</h2></div><Users size={19}/></header>{error?<div className="ag-studio-error">{error}</div>:null}<div className="ag-guests-layout"><div><form className="ag-guest-invite-form" onSubmit={invite}><input value={name} onChange={e=>setName(e.target.value)} placeholder="Guest name" required/><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email (optional)" type="email"/><label><input type="checkbox" checked={sendEmail} onChange={e=>setSendEmail(e.target.checked)}/> Email branded invitation immediately</label><button><UserPlus size={14}/> INVITE GUEST</button></form>{lastLink?<div className="ag-guest-link"><code>{lastLink}</code><button onClick={()=>void navigator.clipboard.writeText(lastLink)}><Copy size={13}/> COPY</button></div>:null}<div className="ag-guest-roster">{guests.length===0?<p className="ag-studio-muted">No guests invited yet.</p>:guests.map(g=><article key={g.id}><div><strong>{g.display_name}</strong><span>{g.studio_people?.email||"Private link only"}</span></div><em className={`state-${g.state}`}>{g.state.replace("_"," ")}</em><div className="ag-guest-row-actions"><button onClick={()=>void act({type:"resend",guestId:g.id})}><Mail size={12}/> NEW LINK + EMAIL</button>{g.state!=="queued"&&g.state!=="live"?<button onClick={()=>void act({type:"state",guestId:g.id,state:"queued"})}>QUEUE</button>:null}{g.state==="queued"?<button onClick={()=>void act({type:"state",guestId:g.id,state:"live"})}>BRING LIVE</button>:null}{g.state==="live"?<button onClick={()=>void act({type:"state",guestId:g.id,state:"green_room"})}>BACKSTAGE</button>:null}</div></article>)}</div></div><div className="ag-producer-chat"><header><MessageCircle size={15}/><strong>Backstage messages</strong></header><div>{messages.slice(-30).map(m=><article key={m.id}><span>{m.sender_role}</span><p>{m.body}</p></article>)}</div><form onSubmit={sendMessage}><select value={target} onChange={e=>setTarget(e.target.value)}><option value="">All guests</option>{guests.map(g=><option key={g.id} value={g.id}>{g.display_name}</option>)}</select><input value={message} onChange={e=>setMessage(e.target.value)} placeholder="Message backstage…"/><button>SEND</button></form></div></div></section>;
}
